install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt\lib\local-preloaded\org.scala-sbt\sbt\0.13.15\jars\sbt.jar" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.zip',
          'C:\sbt-0.13.15.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-0.13.15.zip", "C:\")
      }
  - ps: |
      if (!(Test-Path -Path "C:\Program Files\Java\jdk1.8.0\src.zip")) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://github.com/fommil/openjdk8src/raw/master/src.zip',
          'C:\Program Files\Java\jdk1.8.0\src.zip'
        )
      }
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_HOME=C:\Users\appveyor\.sbt
  - cmd: SET COURSIER_VERBOSITY=-1
  - cmd: SET GC_LOGGING=true
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
build_script:
  - sbt clean compile
test_script:
  - sbt scripted
cache:
  - C:\Program Files\Java\jdk1.8.0\src.zip
  - C:\sbt -> appveyor.yml
  - C:\Users\appveyor\.sbt -> appveyor.yml
  - C:\Users\appveyor\.ivy2 -> appveyor.yml
  - C:\Users\appveyor\.coursier -> appveyor.yml
on_finish:
  - ps: Get-ChildItem -Path .\* -Include *.log,*.hprof -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
